# permissions for end users to edit kernels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jupyter-kernel-controller
    app.kubernetes.io/managed-by: kustomize
  name: kernel-editor-role
rules:
- apiGroups:
  - jupyter.org
  resources:
  - kernels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jupyter.org
  resources:
  - kernels/status
  verbs:
  - get
