apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kernel-controller-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kernel-controller-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: kernel-controller-serviceaccount
  namespace: system
