apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: jupyter-kernel-controller
    app.kubernetes.io/managed-by: kustomize
  name: kernel-controller-serviceaccount
  namespace: system
