apiVersion: jupyter.org/v1
kind: Kernel
metadata:
  labels:
    app.kubernetes.io/name: jupyter-kernel-controller
    app.kubernetes.io/managed-by: kustomize
  name: kernel-sample
spec:
  # TODO(user): Add fields here
