name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'manifests/**'
      - 'kernel_launch/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'manifests/**'
      - 'kernel_launch/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # We use slog which was introduced in Go 1.21, so the minimum version is 1.21
          go-version: '1.22.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: |
          go get .
      - name: Test with Go
        run: go test -json
      - name: Build
        run: go build -v
